.TH CATF 1
.SH NAME \"        Copyright (C) 1989 by Kenneth Almquist.
catf \- concatenate files
.SH SYNOPSIS
.B catf
.I file...
.SH COPYRIGHT
.if n Copyright (C) 1989 by Kenneth Almquist.
.if t Copyright \(co 1989 by Kenneth Almquist.  
.SH DESCRIPTION
Catf copies the files specified as arguments to the standard output.
As a special case, the file name ``-'' causes
.I catf
to read from the standard input.
.SH "HISTORICAL NOTE"
Early versions of UNIX had a program which was very similar to
.IR catf .
It was named
.IR cat .
