.TH LINE 1
.SH NAME \"        Copyright (C) 1989 by Kenneth Almquist.
line \- read a line
.SH SYNOPSIS
.B line
.SH COPYRIGHT
.if n Copyright (C) 1989 by Kenneth Almquist.
.if t Copyright \(co 1989 by Kenneth Almquist.  
.SH DESCRIPTION
.I Line
copies one line from its standard input to its standard output.
If it encounters an end of file before reading a newline, it
outputs a newline character and returns an exit status of 1.
