.TH NLECHO 1
.SH NAME \"        Copyright (C) 1989 by Kenneth Almquist.
nlecho \- echo arguments, one per line
.SH SYNOPSIS
.B nlecho
[
.I arg
] ...
.SH COPYRIGHT
.if n Copyright (C) 1989 by Kenneth Almquist.
.if t Copyright \(co 1989 by Kenneth Almquist.  
.SH DESCRIPTION
.I Nlecho
prints its arguments on the standard output, one argument per line.
